In [2]:
import numpy as np

#Datatype

#Type	說明
#bool	布林值
#int8	8 位元有號整數
#int16	16 位元有號整數
#int32	32 位元有號整數
#int64	64 位元有號整數
#uint8	8 位元無號整數
#uint16	16 位元無號整數
#uint32	32 位元無號整數
#uint64	64 位元無號整數
#float16	16 位元浮點數
#float32	32 位元浮點數
#float64	64 位元浮點數
#complex64	64 位元複數
#complex128	128 位元複數

#numpy陣列屬性

#ndim()：取得陣列的維度數量
#shape()：陣列的形狀
#size()：陣列的數量
#dtype()：資料型態
#itemsize()：陣列中元素的大小(位元組為單位)
#nbytes()：陣列的大小(位元組為單位) 一般來說 nbytes = itemsize * size


In [24]:
#建立1d array
A=np.array([4,5,6]) #ndarray的元素可以用list或tuple輸入,且必須為同類型
print(A)
print(type(A))
A[0]=10
B=np.zeros(6)
print(B)
C=np.ones(6)
print(C)
D=A[1:3] #取1~3(不含)
print(D)
#array的大小一致的話，可以直接做加減乘除的運算，其運算是元素對元素
E=B+C
print(E)

a=np.random.randn(3)  #隨機產生3個數值的一維陣列(0~1的浮點數)
b=np.random.randn(3)  
ironman_random = np.random.random((3,3)) #建立一個3*3 陣列，在0到1間亂數值
b=np.abs(b)
c=np.floor(a)  #為不大於數值的最大整數(element-wise)
d=np.ceil(a)  #為不小於數值的最小整數(element-wise)
e=np.maximum(a,b) #取出a,b中比較大的數值(element-wise)
f=np.sqrt(b) #對每個數值開根號
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

[4 5 6]
<class 'numpy.ndarray'>
[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[5 6]
[1. 1. 1. 1. 1. 1.]
[-0.28515511 -0.77493307 -0.32398274]
[0.48340172 1.35554952 1.34006073]
[-1. -1. -1.]
[-0. -0. -0.]
[0.48340172 1.35554952 1.34006073]
[0.69527097 1.16428069 1.15760992]


In [21]:
#numpy.arange(start, stop, step, dtype)  此陣列以等差數列的形式產生
#  start : 從某數開始，預設為0
#  stop : 到某數停止(不包含)
#  step : 間格多少
#  dtype : bool(布林值), int(整數), float(浮點數), complex(複數)
#    1）一个参数时，参数值为终点，起点取默认值0，步长取默认值1。
#    2）两个参数时，第一个参数为起点，第二个参数为终点，步长取默认值1。
#    3）三个参数时，第一个参数为起点，第二个参数为终点，第三个参数为步长。其中步长支持小数

F=np.arange(50,60,3,int)
print(F)
f=np.arange(3)
print(f)

#np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None) 此陣列以等比數列的形式產生
#  start : 從某數開始
#  stop : 到某數停止
#  num : start到stop之間有多少數字
#  endpoint : True(包含stop); False(不包含stop)，預設為True
#  base : 以多少為底數，預設為10.0
#  dtype : bool(布林值), int(整數), float(浮點數), complex(複數)

[50 53 56 59]
[0 1 2]


In [14]:
#2d array

G=np.array([[1,2,3],[4,5,6]]) #外面需有一層
print(G)
H=G.T;
print(H) #transpose

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [18]:
#矩陣乘法,內積,外積

#矩陣乘法（不能直接用＊,那樣是element-wise的）
I=G.dot(H)
print(I)

J=np.array([1,2,2,2,2,1])
K=np.array([5,6,7,8,9,10])

L=np.inner(J,K)
print(L)

M=np.outer(J,K)
print(M)

[[14 32]
 [32 77]]
75
[[ 5  6  7  8  9 10]
 [10 12 14 16 18 20]
 [10 12 14 16 18 20]
 [10 12 14 16 18 20]
 [10 12 14 16 18 20]
 [ 5  6  7  8  9 10]]


In [34]:
#改變型態

a1=a.astype(np.int32)  #將a的type改成int32，並指派給a1(a不會改到！！！)
print(b.dtype)
print(b)
b1=b.astype(a1.dtype)  
print(c.dtype);
c=c.astype(np.int32)
print(b.dtype)
print(b1.dtype)
print(b1)
print(c.dtype)

float64
[0.48340172 1.35554952 1.34006073]
int32
float64
int32
[0 1 1]
int32


In [38]:
#布林遮罩:用一個判斷式，判斷是Ture還是Flase，常常用來做資料的分析
#舉個例子來說，現在有十萬筆的薪資資料，可以使用布林遮罩的方式將大於平均薪資的資料留下

x=np.array([1,2,3,4,5])
print(x>2) #按元素判斷
print(x[x>2]) #將符合條件的元素取出
y=x[x>2] #將符合條件的元素取出並賦給y
print(y)
x[x>2]=99 #將符合條件的元素改成某值
print(x)


[False False  True  True  True]
[3 4 5]
[3 4 5]
[ 1  2 99 99 99]


In [ ]:
#slice

#連續選取：選取索引值a到b的資料x[a:b]
#a：選取資料的起始索引，不指定表示從頭開始
#b：選取資料的結束索引+1，不指定表示直到陣列結束

#間隔選取：x[a:b:c]
#a：選取資料的起始索引
#b：選取資料的結束索引+1
#c：選取資料間隔，以索引值可以被此值整除的元素，不指定表示1

#倒序[::-1]
#只是單純的把順序反過來，並無數值大小比較

#特別用法
a = np.array([[1, 2, 3, 4, 5], 
              [6, 7, 8, 9, 10], 
              [11, 12, 13, 14, 15], 
              [16, 17, 18, 19, 20], 
              [21, 22, 23, 24, 25]])
              
b = a[(0, 1, 2, 3, 4), (1, 1, 2, 3, 4)] # 取出(0,1),(1,1),(2,2),(3,3),(4,4)的元素
c = a[2:, [0, 2]] # 取出第2列以後，第0行及第2行的所有元素
d = a[3:, 3:] # 取出第三列以後，第3行以後的所有元素

In [4]:
#reshape
x = np.array([1,2,3])
x_reshape = x.reshape((3,1)) #改成3列1行 (不會動到x)
print(x_reshape)
print(x)

b = np.arange(1, 13).reshape(3, 4)  #可以合體（？）
print(b)


[[1]
 [2]
 [3]]
[1 2 3]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [44]:
#統計性質

#sum
a = np.linspace(1,20,20).reshape(4,5)
print(a)
q=np.sum(a)  #全部元素加起來  等同a.sum() (不會改到a)
print(q)
w=np.sum(a,axis = 1)  #axis为1為紀錄每列的total  等同a.sum(axis=1) (不會改到a)
print(w)
e=np.sum(a,axis = 0)  #axis为0為紀錄每行的total  等同a.sum(axis=0) (不會改到a)
print(e)

#max,min,mean
max_=a.max()  #等同np.max(a)
print(max_)
min_=a.min()
print(min_)
mean_=a.mean()
print(mean_)
std_=a.std() #變異數
print(std_)
var_=a.var() #標準差
print(var_)




[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]
210.0
[15. 40. 65. 90.]
[34. 38. 42. 46. 50.]
20.0
20.0
1.0
10.5


In [47]:
#排序
print(a)
a.sort()  #ascending
print(a)


[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]
